### ISSUE TITLE
UML diagram (Sequence diagram)

### ISSUE THREAD

**Issue by zw-weng** [drshahizan/software-engineering#142]
Jie Sheng has done drawing all the sequence diagrams related to each of the use case in order to describes how and in what order a system function works.

Duration: 9/5/2023 to 14/5/2023
Tool used: drawio
Sequence diagrams:

**Comment by jiesheng4616** [comment]
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/b041a7e1-b20d-4e4e-8904-00f0b1d4d332)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/541f57b9-72c3-4545-9e72-4d18f0d77fcc)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/662c41b6-1dfe-4b5a-be21-014bb9a933fa)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/ce361d91-0e30-417c-abe5-bbd3f506cfcc)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/e26ebcf5-63d7-4833-8b1d-f75bf8227833)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/d6feb456-00e5-4476-8134-5533f7141a96)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/486ce6fd-ce60-44a5-bb93-828e20a84fa7)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/62e2fed3-ecbc-44ab-8604-341d0d6bdbb2)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/c9174649-5abf-4707-940d-ab61505769f1)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/bccf7ea2-8499-41fa-a6ce-940e8b58dfd0)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/24b0c084-02fb-46dc-9664-257295ee3c49)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/b0cb3838-41d4-495b-8825-4c90b8f41140)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/78b822de-c791-4254-9ded-179644eeb860)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/6d2d2911-a2fb-476e-be51-6322cb1d1e28)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/d0bcd13c-c61a-49af-b5db-76d27dea8c74)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/8b2e6304-f494-4ff6-b074-757b20a52768)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/4adab99f-362a-4e1a-a27f-467605c3e3f6)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/823287e3-e9b6-43d2-b63a-dd65a0e16932)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/7a228719-0a55-48bd-a9a7-bdae10122272)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/1593e8d1-1576-4945-a090-80624ae3bdac)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/2acc7778-5c28-45e3-9a77-1d9155b3a009)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/0f7cec4a-6cb3-4448-aee5-27107ee095bf)
![Image](https://github.com/drshahizan/software-engineering/assets/129199459/351c369c-fddf-477d-a1ba-5e161875c263)
