### ISSUE TITLE
UML diagram (Activity diagram)

### ISSUE THREAD

**Issue by zw-weng** [drshahizan/software-engineering#143]
Total Activity diagram is 23 because we have 23 use case

**Comment by daniallllllll** [comment]
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/1d4e1bef-4309-4b30-93a6-2ec74cdfbfa9)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/0fdec033-407c-4b02-905c-00709b69b1dd)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/e4bd5b8e-27ee-48b6-a84e-d47e8527c5d1)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/248997dd-dd29-426a-b59a-bb98cc74ff92)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/4d3d389f-e49b-491c-b515-eb7513c4a8d2)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/41765545-1254-4122-906c-03dd70291504)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/e519fe00-5ae9-4529-a2e2-bf61098fc870)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/b039fd6a-0ade-418f-ac9d-aeda7094fa60)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/36e10ebb-50e7-43d1-9a9a-9428dc32d949)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/c6222bdf-51d8-4390-9393-ffebcf45ff83)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/4959a83f-7339-45d4-abef-06f3d8ee4633)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/77a54d3f-8a35-4115-9805-7146c19f4769)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/3ec07905-91bc-4b07-befd-59765432704a)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/73142163-af83-4460-913e-709ad24f717f)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/ff467eea-5b13-43a2-8668-30066e341081)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/c0bda853-8ce4-47fd-99e8-0bab61313cf5)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/64528d20-4589-40a0-b3e2-c0c8148351e8)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/da2dd147-3bd8-4e86-9384-6505122a9104)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/93f47969-ee64-414e-9313-d5651d2477c9)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/79efbe11-58f2-458b-938a-798bfac879fa)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/2069b181-b36f-4d29-935a-90f770afb4ba)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/97407d04-717d-47d1-8def-a74fea5634cd)
![Image](https://github.com/drshahizan/software-engineering/assets/129204039/d02fb1f8-a125-4940-b298-a7501064a127)
