### ISSUE TITLE
Create Project Plan

### ISSUE THREAD

**Issue by Jingyong14** [drshahizan/software-engineering#16]

**Comment by wei2030** [comment]
Set up a meeting with all group member to decide the software system to be develop. Determine the role of each member and have a rough plan for this project.

Discussion outcome:

1. Decide to engage the UTM student feedback system
2. Created a plan for project timeline
3. Role Distribution for this system
4. Determine the target stakeholder for this system


![Image](https://github.com/drshahizan/software-engineering/assets/89129564/9c25edb2-52dd-4fc8-8707-ebe047f0e617)



![Image](https://github.com/drshahizan/software-engineering/assets/89129564/6d249823-5fad-4f6d-ba4a-cd06b2893ca2)
