### ISSUE TITLE
Create UML Diagram

### ISSUE THREAD

**Issue by LeeSoonDer** [drshahizan/software-engineering#26]
Create Use case Diagram,Class Diagram,Sequence diagram and Activity Diagram for SRS document

**Comment by Jingyong14** [comment]
All diagrams has been created and commited into drawio file in github



![Image](https://github.com/drshahizan/software-engineering/assets/89129564/2bed92c6-032d-4a4f-a173-fd44043d5b4f)





![Image](https://github.com/drshahizan/software-engineering/assets/129235577/dbe3ca58-0485-462e-bb2a-bc9558d580a1)

**Comment by Jingyong14** [comment]
![Image](https://github.com/drshahizan/software-engineering/assets/129235577/009fc73b-0e8a-48f4-bc53-9f0ea7242197)

![Image](https://i.imgur.com/O6h9rw2.jpg)
