### ISSUE TITLE
Project planning

### ISSUE THREAD

**Issue by josephlau2003** [drshahizan/software-engineering#28]

**Comment by zw-weng** [comment]
We have done a group meeting to discuss our project plan and role distribution via online Google Meet.

Date: 18/4/2023
Duration: 3 hours
Platform: Google Meet

Meeting outcomes: 

- Decision on developing of a Student Accommodation System in Kolej Tun Dr Ismail (KTDI)

-  Project timeline and roadmap

-  Member role distribution
<table>
  <tr>
    <th>Name</th>
    <th>Role</th>
  </tr>
  <tr>
    <td>Neo Zheng Weng</td>
    <td>Project Manager & UI/UX System Designer</td>
  </tr>
  <tr>
    <td>Wong Khai Shian Nicholas</td>
    <td>Requirements Analyst & Developer Assistant</td>
  </tr>
    <tr>
    <td>Muhammad Danial</td>
    <td>Documentation Specialist & Developer Assistant</td>
  </tr>
    <tr>
    <td>Joseph Lau Yeo Kai</td>
    <td>IT Support & Main Developer</td>
  </tr>
  <tr>
  <td>Low Jie Sheng</td>
  <td>Quality Assurance Analyst & Developer assistant</td>
  </tr>
</table>

![Image](https://user-images.githubusercontent.com/118497269/235573719-e1a0c36a-f5be-401b-b9fd-5f0430a3eb30.png)
