### ISSUE TITLE
Meeting with stakeholder 4 (KTDI Staff)

### ISSUE THREAD

**Issue by josephlau2003** [drshahizan/software-engineering#37]

**Comment by daniallllllll** [comment]
Photo with Mr Mohamad Bin Yunos

![Image](https://github.com/drshahizan/software-engineering/assets/129204039/4f9a038f-ad73-488c-8e3e-d519c9520253)

**Comment by zw-weng** [comment]
We have done a short meeting with our KTDI staff stakeholder **(Mr Mohamad Bin Yunos)**. He has provided us the manual KTDI forms for each type of applications and also given us an insight on current application system and the new features wanted in our new web app software product.

Meeting outcome:
- KTDI manual application forms:

![Image](https://github.com/drshahizan/software-engineering/assets/118497269/425fc037-3395-4768-84e9-ef09c7285003)
![Image](https://github.com/drshahizan/software-engineering/assets/118497269/050e6533-6ebe-4e93-b3bf-22602a6feb47)
![Image](https://github.com/drshahizan/software-engineering/assets/118497269/78819890-6c1a-4beb-a98c-8437f5ddfc35)
![Image](https://github.com/drshahizan/software-engineering/assets/118497269/2e2f1bcd-750e-4128-a2bb-4144f4e909fa)
![Image](https://github.com/drshahizan/software-engineering/assets/118497269/ee375d31-a58a-4724-97a0-bab0cc64ffab)
