### ISSUE TITLE
Software Design Document

### ISSUE THREAD

**Issue by josephlau2003** [drshahizan/software-engineering#38]

**Comment by zw-weng** [comment]
### Task Distribution on SDD

1. P001 Authentication module - Neo
2. P002 Centralised dashboard module, P003 Reporting and analytics module - Low
3. P004 Room management module - Danial
4. P005 Room application module - Joseph
5. P006 Payment management module - Nicholas

- System architectural design - Neo
- Complete package diagram - Danial
- Data design - Joseph
- User interface design - Nicholas
