### ISSUE TITLE
Develop UML Activity Diagram and sequence diagram

### ISSUE THREAD

**Issue by oishylea** [drshahizan/software-engineering#46]

**Comment by nikzulaikhaa** [comment]
Sequence Diagram
![Image](https://github.com/drshahizan/software-engineering/assets/128201865/2151c763-1c80-4984-ae28-8f26a55224aa)

Delivery
![Image](https://github.com/drshahizan/software-engineering/assets/128201865/6ae171b7-08b1-44c3-99ce-91d6d4091510)

OPC
![Image](https://github.com/drshahizan/software-engineering/assets/128201865/7f51afc8-ad97-477c-a574-c59857394d35)
