### ISSUE TITLE
First interview with Dr. Nur Eiliyah Wong

### ISSUE THREAD

**Issue by nicolelimty** [drshahizan/software-engineering#55]

**Comment by jjwong2003** [comment]
![Image](https://github.com/drshahizan/software-engineering/assets/129287788/416584ed-7a60-41d5-8cd6-d26cdfd03fdd)
![Image](https://github.com/drshahizan/software-engineering/assets/129287788/05d1f56a-8140-4b31-9fcd-c64842cfc726)
