### ISSUE TITLE
Meeting with stakeholder 2 (Student 1)

### ISSUE THREAD

**Issue by daniallllllll** [drshahizan/software-engineering#63]

**Comment by zw-weng** [comment]
We have done a meeting with our student stakeholder **(Mr Muhammad Izzat Haziq bin Rumaizi)** via online meeting on Google Meet. He has provided the feedbacks for the current KTDI accommodation system and providing the ideas for the upgraded accommodation system, mainly in the application system for room management.

### Meeting info:

- Date: 22/5/2023
- Stakeholder: UTM student
- Role: KTDI resident
- Name: Muhammad Izzat Haziq bin Rumaizi

### Meeting outcome:

- A dashboard designed room action application page (eg. room changing, cancellation, check in/out).
- Digitalized and user friendly user interfaces.

### Photo with Mr Muhammad Izzat Haziq bin Rumaizi:
![Image](https://github.com/drshahizan/software-engineering/assets/129279911/ee202b44-05f3-471b-b882-1489663ba6a6)
