### ISSUE TITLE
Meeting with stakeholder 2 (Student 2)

### ISSUE THREAD

**Issue by daniallllllll** [drshahizan/software-engineering#64]

**Comment by nicholas0377** [comment]
nice

**Comment by zw-weng** [comment]
We have done a meeting with our student stakeholder **(Mr Hayden Huan Kee Jiun)**. He has given us the feedbacks for the current KTDI accommodation system and providing the ideas for the upgraded accommodation system, mainly in maintenance system (requesting and tracking).

###  Meeting info:

- Date: 22/5/2023
- Stakeholder: UTM student
- Role: KTDI resident
- Name: Hayden Huan Kee Jiun

###  Meeting outcome:

- Google Form for requesting maintenance in KTDI (Current):
https://forms.gle/AiMF5gJ9yYyBQVZw6

- Digitalized online application form
- Simple tracking feature with color labeled

###  Photo with Mr Hayden Huan Kee Jiun:
![Image](https://github.com/drshahizan/software-engineering/assets/129279911/8d2b7514-7cbc-4803-97ba-d81e96ff77d2)
