### ISSUE TITLE
Scrum Meeting

### ISSUE THREAD

**Issue by zw-weng** [drshahizan/software-engineering#84]
We have conducted a scrum stand-up which is a 15-minute daily meeting held throughout the sprint to discuss progress and promptly address any issues. It ensures all the members are in-line with the latest project progress.

Meeting content is as following:
1. What have you achieved since the previous meeting?
2. What tasks are you currently working on before the next meeting?
3. What obstacles or challenges are hindering your progress or preventing you from completing your tasks?

### 1st Scrum Meeting:
- Date: 28/5/2023
- Venue: Computer security lab

![Image](https://github.com/drshahizan/software-engineering/assets/118497269/c5ae852a-52cb-469f-8a2f-6b86594898a0)

**Comment by nicholas0377** [comment]
### 2nd Scrum Meeting:

-  Date: 29/5/2023

-  Venue: Google Meet (online meeting)



![Image](https://github.com/drshahizan/software-engineering/assets/129279911/cc118b96-0859-496d-85dd-8e6657b3ddd3)





### 3rd Scrum Meeting:

-  Date: 30/5/2023

-  Venue: Computer security lab

![Image](https://github.com/drshahizan/software-engineering/assets/129279911/df65e0be-82bd-44b7-ad69-3aa4c45dd590)

**Comment by nicholas0377** [comment]
testing

**Comment by nicholas0377** [comment]
### 4th Scrum Meeting:
- Date: 31/5/2023
- Venue: Google Meet (online meeting)



![Image](https://github.com/drshahizan/software-engineering/assets/129279911/30268a21-4a7f-40de-a2ff-48fc10dc6685)

**Comment by nicholas0377** [comment]
### 5th Scrum Meeting:
- Date: 2/6/2023
- Venue: Google Meet (online meeting)


![Image](https://github.com/drshahizan/software-engineering/assets/129279911/8c15d49a-cd4e-4391-aa48-a4078f95cc60)

**Comment by nicholas0377** [comment]
### 6th Scrum Meeting:
- Date: 6/6/2023
- Venue: Google Meet (online meeting)


![Image](https://github.com/drshahizan/software-engineering/assets/129279911/c08759c9-4a4f-4a31-811d-cf25bc4b5458)

**Comment by zw-weng** [comment]
### 7th Scrum Meeting:
- Date: 8/6/2023
- Venue: Google Meet (online meeting)



![Image](https://github.com/drshahizan/software-engineering/assets/118497269/3521e441-83c5-48d9-afb7-99ee1ecdff01)

**Comment by nicholas0377** [comment]
### 8th Scrum Meeting:
- Date: 12/6/2023
- Venue: Google Meet (online meeting)



![Image](https://github.com/drshahizan/software-engineering/assets/129279911/50780c83-8502-4321-bef8-8f04f0a5d61d)
