### ISSUE TITLE
Low Fidelity Progression

### ISSUE THREAD

**Issue by ariffdanish** [drshahizan/software-engineering#89]
Here are some of our progress pics on low fidelity.

<img src="https://github.com/drshahizan/software-engineering/assets/128123046/35008ff5-eb5d-4ace-9ea2-0518697e45c0" width="400">
<img src="https://github.com/drshahizan/software-engineering/assets/128123046/43284846-ff59-458a-9177-3aa7dc6a7479" width="400">
<img src="https://github.com/drshahizan/software-engineering/assets/128123046/b4c102cd-015f-4d06-ac54-5a59cfc6aa39" width="400">
<img src="https://github.com/drshahizan/software-engineering/assets/128123046/a99db4ba-f9f7-4c12-bcaf-37805ff12202" width="400">
<img src="https://github.com/drshahizan/software-engineering/assets/128123046/78f64743-0b93-40a3-b042-8156b6b28d7d" width="400">

**Comment by akim730** [comment]
/
