### ISSUE TITLE
High Fidelity Progression

### ISSUE THREAD

**Issue by ariffdanish** [drshahizan/software-engineering#90]
https://www.figma.com/file/kKC8pg0ilTBncv1txpu6Yp/Login-(Community)?type=design&node-id=0%3A1&t=1XQ3NhOlBKKZW0P5-1

![Image](https://github.com/drshahizan/software-engineering/assets/128231261/6af46ed1-ced0-4a53-b3a1-4aa635c7b5e0)

<img src="https://github.com/drshahizan/software-engineering/assets/128231261/f14193f9-0b87-4377-ad8d-312125ed2a89" alt="Image 2" style="border: 1px solid black; width: 400px;">

<img src="https://github.com/drshahizan/software-engineering/assets/128231261/738f56a9-eec8-4c2d-af62-c4e399480669" alt="Image 3" style="border: 1px solid black; width: 400px;">

<img src="https://github.com/drshahizan/software-engineering/assets/128231261/36b2d277-64eb-4ee9-aacf-94a644beab51" alt="Image 4" style="border: 1px solid black; width: 400px;">

<img src="https://github.com/drshahizan/software-engineering/assets/128231261/20478acb-481e-4503-bcfd-1fa7b27dc880" alt="Image 5" style="border: 1px solid black; width: 400px;">

<img src="https://github.com/drshahizan/software-engineering/assets/128231261/7386c380-ba9d-4773-ac3a-d5c56579d1e4" alt="Image 6" style="border: 1px solid black; width: 400px;">

**Comment by akim730** [comment]
@ariffdanish @akim730
