### ISSUE TITLE
System Design

### ISSUE THREAD

**Issue by tiewrong** [drshahizan/software-engineering#92]
1. Create information architecture
2. Create user flow
3. Create low fidelity 
4. Create high fidelity
5. Create UI/UX design

**Comment by tiewrong** [comment]
<b>Information architecture</b>

<b>Student:</b>
<img src="https://github.com/drshahizan/software-engineering/assets/129280403/b36d9933-0a33-4a90-841e-8feebf6f6a7a">



<b>Lecturer:</b>
<img src="https://github.com/drshahizan/software-engineering/assets/129280403/adc4c2bc-3065-4641-8b1b-3214f5e2e0a5">



<b>Admin:</b>
<img src="https://github.com/drshahizan/software-engineering/assets/129280403/521baeca-e831-43a3-9cb8-1a0407b928dc">

**Comment by tiewshen** [comment]
User flow :


![Image](https://github.com/drshahizan/software-engineering/assets/129257370/0c9d8f7d-6eae-4d4c-8eee-0cb8844f1731)
