### ISSUE TITLE
create low fidelity

### ISSUE THREAD

**Issue by tiewrong** [drshahizan/software-engineering#93]

**Comment by tiewrong** [comment]
We start to create low fidelity after the discussion

**Comment by nicolelimty** [comment]
[

![Image](https://github.com/drshahizan/software-engineering/assets/129235052/19357b02-d39b-4e40-9379-9d4e1d50a384)
![Image](https://github.com/drshahizan/software-engineering/assets/129235052/c26aa76d-924e-481b-bd3f-b5739e222018)
![Image](https://github.com/drshahizan/software-engineering/assets/129235052/66706fea-3631-4dda-8c56-04b7458ba9bf)
![Image](https://github.com/drshahizan/software-engineering/assets/129235052/c6d61e9b-eb9d-4c26-9975-deda548f29e6)

](url)
